project:
  type: default
  preview:
    browser: true
    watch-inputs: true
    navigate: true

resources:
  - robots.txt

format:
  html:
    smooth-scroll: true
    html-math-method: mathjax
    # theme: cosmo
    theme: litera
    css: book.css
    toc: true
    number-sections: false
