project:
  type: manuscript
  preview:
    browser: true
    watch-inputs: true
    navigate: true
  render:
    - "index.qmd"       # Includes all your quarto manuscript
    - "*.md"        # Includes other markdown files if you need them
    - "!BUILD.md"   # Explicitly ignores BUILD.md

resources:
  - robots.txt

format:
  html:
    smooth-scroll: true
    html-math-method: mathjax
    # theme: cosmo
    theme: litera
    css: article.css
    toc: true
    number-sections: false
  
